// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'register_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'register_model.g.dart';

@unfreezed
class RegisterModel with _$RegisterModel {
  factory RegisterModel({
    required String? name,
    String? id,
    required String? registrationNo,
    required String? phone,
    required String? address,
    required String? department,
    required String? password,
    required String? departmentId,
    required String? personId,
    required String? gender,
    required String? urlImage,
    required String? email,
    required String? staffId,
    required String? studentId,
    required String? count,
    required String? vehicleId,
    String? long,
    String? lat,
  }) = _RegisterModel;

  factory RegisterModel.fromJson(Map<String, Object?> json) =>
      _$RegisterModelFromJson(json);
}
