// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'vehicle_operation_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'vehicle_operation_model.g.dart';

@freezed
class VehicleOperationModel with _$VehicleOperationModel {
  const factory VehicleOperationModel({
    required String? trip_in_progress,
    required String? vehicle_in_queue,
    required String? completed_trips,
    required String? cummuter_statistics,
    required String? destination,
    required String? daily_no_trip,
    required String? time,
    required String? date,
  }) = _VehicleOperationModel;

  factory VehicleOperationModel.fromJson(Map<String, Object?> json) =>
      _$VehicleOperationModelFromJson(json);
}
