// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'vehicle_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'vehicle_model.g.dart';

@freezed
class VehicleModel with _$VehicleModel {
  const factory VehicleModel({
    required String? uId,
    required String? id,
    required String? ownderId,
    required String? name,
    required String? model,
    required String? type,
    required String? plateNumber,
    required String? count,
    required String? phoneNumber,
    required String? capacity,
    required String? address,
    required String? date,
    String? imageUrl,
  }) = _VehicleModel;

  factory VehicleModel.fromJson(Map<String, Object?> json) =>
      _$VehicleModelFromJson(json);
}
