// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'booking_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'booking_model.g.dart';

@unfreezed
class BookingModel with _$BookingModel {
  factory BookingModel({
    required String? source,
    required String? destination,
    required String? departureDate,
    required String? departureTime,
    required String? bookinRef,
    required String? date,
    required String? time,
    required String? progress,
    required double? latS,
    required double? longS,
    required double? latD,
    required double? longD,
    String? driverName,
    String? driverId,
    String? driverStaffId,
    String? studentName,
    int? noPassenger,
  }) = _BookingModel;

  factory BookingModel.fromJson(Map<String, Object?> json) =>
      _$BookingModelFromJson(json);
}
