// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'my_images.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'my_images.g.dart';

@freezed
class MyImage with _$MyImage {
  const factory MyImage({
    required String? name,
    required String? link,
  }) = _MyImage;

  factory MyImage.fromJson(Map<String, Object?> json) =>
      _$MyImageFromJson(json);
}
